"""Initial migration

Revision ID: 890726b511bd
Revises: 001_initial
Create Date: 2025-05-14 07:17:33.824401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890726b511bd'
down_revision = '001_initial'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_recommendation_items_id'), 'recommendation_items', ['id'], unique=False)
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_saved_models_id'), 'saved_models', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_models_id'), table_name='saved_models')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendation_items_id'), table_name='recommendation_items')
    # ### end Alembic commands ###
